user:
  name: 梦奇刘
  
server:
  port: 8081 

spring:
  application:
    name: web
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 192.168.1.112
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        
feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.112:8761/eureka