user:
  name: 奇梦刘

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 192.168.1.11
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
       
feign:
  hystrix:
    enabled: true